### ISSUE TITLE
Reveals characters with ANSI escape sequences

### ISSUE THREAD

**Issue by tmpfs** [isaacs/mute-stream#3]
When using the `read` module in silent mode with an ANSI formatted prompt and setting a *replace* character upon the backspace keypress event the *replace* character is no longer respected, ie, the plain text is displayed on screen.

Without ANSI escape sequences this issue is not present.

I tracked this down to the `write` method and have implemented a fix, within the ANSI conditional clause (https://github.com/isaacs/mute-stream/blob/master/mute.js#L103) I added:

```
if(c.indexOf(this._prompt) === 0) {
  var text = c.replace(this._prompt, '');
  text = text.replace(/./g, this.replace);
  c = this._prompt + text;
}
```

I am using a modified version of the `read` module which allows passing the unformatted prompt length when calling `ReadlineInterface.setPrompt()` (https://github.com/joyent/node/issues/3860).

```
node --version => v0.10.29
```

The patched version of `mute-stream` is here:

https://github.com/freeformsystems/cli-input/blob/master/lib/mute.js

Interested in a pull request?

**Comment by tmpfs** [comment]
Thank you so much, I thought you would never get around to this! I nearly emailed you after the state of npm email but I imagined you are very busy ;)

**Comment by isaacs** [comment]
I'm on vacation this week, so I found some time to look at a few OSS things :)
